package de.c4vxl.enums

enum class Permission {
    ALL,
    FEATURE_EMBED,
    FEATURE_CHANNELS_VOICE,
    FEATURE_CHANNELS_TEXT,
    FEATURE_CHANNELS_UNLIMITED,
    FEATURE_CHANNELS_BUTTONS,
    FEATURE_RULES_MOD,
    FEATURE_TICKETS_VIEW,
    FEATURE_TICKETS_MANAGE,
    FEATURE_TICKETS_OPEN,
}