package de.c4vxl.enums

enum class Permission {
    ALL,
    FEATURE_EMBED,
    FEATURE_CHANNELS_VOICE,
    FEATURE_CHANNELS_TEXT,
    FEATURE_CHANNELS_UNLIMITED,
    FEATURE_CHANNELS_BUTTONS,
    FEATURE_RULES_MOD
}