package de.c4vxl.config.enums

enum class Permission {
    ALL,
    FEATURE_EMBED,
    FEATURE_CHANNELS_VOICE,
    FEATURE_CHANNELS_TEXT,
    FEATURE_CHANNELS_UNLIMITED,
    FEATURE_CHANNELS_BUTTONS,
    FEATURE_CHANNELS_PRESET,
    FEATURE_RULES_MOD,
    FEATURE_TICKETS_VIEW,
    FEATURE_TICKETS_MANAGE,
    FEATURE_TICKETS_OPEN,
    FEATURE_ACTIVITIES,
    FEATURE_ACTIVITIES_MANAGE,
    FEATURE_BE_REAL,
    FEATURE_BE_REAL_MANAGE,
}